---
apache_ssl_ciphers:
  - ECDHE-ECDSA-AES128-GCM-SHA256
  - ECDHE-RSA-AES128-GCM-SHA256
  - ECDHE-ECDSA-AES256-GCM-SHA384
  - ECDHE-RSA-AES256-GCM-SHA384
  - ECDHE-ECDSA-CHACHA20-POLY1305
  - ECDHE-RSA-CHACHA20-POLY1305
  - DHE-RSA-AES128-GCM-SHA256
  - DHE-RSA-AES256-GCM-SHA384

apache_ssl_protocols:
  - "all"
  - "-SSLv3"
  - "-TLSv1"
  - "-TLSv1.1"

apache_ssl_extra: |
  SSLUseStapling on
  SSLStaplingResponderTimeout 5
  SSLStaplingReturnResponderErrors off
  SSLStaplingCache shmcb:/var/run/ocsp(128000)

  SSLCompression off
  SSLSessionTickets off

apache_default_mods_enabled:
  - ssl
  - headers

apache_ssl_options: Header always set Strict-Transport-Security "max-age=15768000"
