---
bearwall2_loopback_class:
  name: loopback
  policies: |
    policy inout accept
  if_features:
    rp_filter: 1
    accept_redirects: 0
    accept_source_route: 0
    bootp_relay: 0
    accept_ra: 0
    forwarding: 0
    log_martians: 0
    send_redirects: 0
