---
sshd_skip_defaults: true
sshd_config_base:
  HostKey:
    - "/etc/ssh/ssh_host_ed25519_key"
    - "/etc/ssh/ssh_host_rsa_key"
    - "/etc/ssh/ssh_host_ecdsa_key"
  KexAlgorithms: "curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256"
  Ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
  MACs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"
  AuthenticationMethods: "publickey"
  LogLevel: "VERBOSE"
  Subsystem: "sftp  /usr/lib/sftp-server -f AUTHPRIV -l INFO"
  PermitRootLogin: "without-password"
  UsePAM: "yes"
  PrintMotd: "no"
  PrintLastLog: "yes"
sshd_config_use_privilege_separation: >-
  {{ {} if
  (ansible_distribution == "Ubuntu" and ansible_distribution_version is version('18.04', '>=')) or
  (ansible_distribution == "Debian" and ansible_distribution_version is version('10', '>='))
  else { "UsePrivilegeSeparation": "sandbox" } }}
sshd: "{{ [
    sshd_config_base,
    sshd_config_use_privilege_separation,
    sshd_config_x11_forwarding | default({}),
    sshd_config_ldap | default({}),
  ] | combine }}"
